config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'

  devise_for :users,
  :controllers => {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :blogs do
    resources :comments
  end

  get 'coach_lp' => 'blogs#coach_lp'
  get 'myself_lp' => 'blogs#myself_lp'

  resources :tags do
    get 'blogs', to: 'blogs#search'
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_one_attached :avatar

  has_rich_text :content

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_blog_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_blog_tag
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy]
  # before_action :guest_log_in, only: %i[ new edit create update destroy]

  # GET /blogs or /blogs.json
  def index
    @tag_list = Tag.all
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blog_tags = @blog.tags
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    # @blog.images.build
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    tag_list = params[:blog][:tag_name].split(nil)

    respond_to do |format|
      if @blog.save
        @blog.save_tag(tag_list)
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    tag_list = params[:blog][:tag_name].split(nil)

    respond_to do |format|
      if @blog.update(blog_params)
        @blog.save_tag(tag_list)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @blogs = @tag.blogs.all
  end

  def coach_lp; end

  def myself_lp; end

  private

    # def guest_log_in
    #   redirect_to root_path if current_user.email == 'guest@example.com'
    # end

    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :avatar)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.file_field :avatar %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class='field'>
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
  </div>

  <div class='field'>
    <%= f.label :tag_name %>
    <%= f.text_field :tag_name %>
  </div>

  <div class="actions mt-3">
    <%= f.submit "保存する", class: 'btn btn-block btn-success btn-sm' %>
  </div>
<% end %>

app/views/blogs/coach_lp.html.erb
<!doctype html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


  <%= stylesheet_link_tag 'reset' %>
  <%= stylesheet_link_tag 'style' %>
  <%= stylesheet_link_tag 'common' %>
  <%= stylesheet_link_tag 'coach_lp' %>
  <%= stylesheet_link_tag 'scaffolds' %>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

  <title>Tatsurocoach</title>

</head>


<body>
  <div class="wrap">
    <main>
      <!-- KV -->
      <div class="kv-wrapper" id="menu-top">
        <div class="kv-text-wrapper">
          <div class="kv-text text-center">
            <div class="kv-copy-top bg">たった60分で</div>
            <h2 class="kv-copy-main">
              自分らしさを<br>
              確実に<br>
              取り戻す
            </h2>
            <div class="kv-copy-bottom">
              <span class="un-li">一日に自分のことを考えている時間は何分ですか？<br>
                10分未満であれば今すぐ相談を！</span>
            </div>
          </div>
        </div>
        <div class="kv-img">
          <img class="top-image" src="images/profile-img-min.JPG" alt="画像の表示に失敗しました">
          <h3 class="Headline kv-text">たつろうコーチ</h3>
        </div>
      </div>

      <!-- message -->
      <div class="message-wrapper">
        <div class="message-inner">
          <h2 class="message-top text-center">こんなモヤモヤありませんか？</h2>
          <ul class="message-list">
            <li class="message-item">
              <div class="message-img-wrapper">
                <img src="./images/k0763_1.png" alt="">
              </div>
              <h3 class="message">
                やりたいことがみつからず<br>
                ぼーっとしていたら1日終えている
              </h3>
            </li>
            <li class="message-item">
              <div class="message-img-wrapper">
                <img src="./images/k0269_2.png" alt="">
              </div>
              <h3 class="message">
                好きなことやワクワクすることで<br>
                生きていきたい.......
              </h3>
            </li>
            <li class="message-item">
              <div class="message-img-wrapper">
                <img src="./images/k0070_0.png" alt="">
              </div>
              <h3 class="message">
                自分の強みを活かして働きたい。<br>
                そのそも自分の強みってなんだろう...
              </h3>
            </li>
          </ul>
          <h2 class="message-bottom text-center">一緒にあなたにしかない<br class="br-sp">
            「あなたらしさ」を取り戻しましょう</h2>
        </div>
      </div>



      <!-- LINEの文言 -->
      <div class="wrapper">
        <div class="top">
          <div class="top-sentences">
            <p class="top-sentence_top sentence-margin-bottom" id="menu-line">たつろうコーチ</p>
            <p class="top-sentence_bottom">
              コーチ / コーチングトレーナー<br>
              <span class="font-green">公式LINEアカウント</span>
            </p>
          </div>
          <div class="line">
            <div class="line-sentences">
              <div class="diagonal-left"></div>
              <div class="line-sentence">
                <p class="sub-line-sentence">登録してくれたあなただけに</p>
                <p class="main-line-sentence">
                  毎月4人限定！3秒でできるLINE登録で<br>
                  限定セッションを無料でプレゼント！
                </p>
              </div>
              <div class="diagonal-right"></div>
            </div>
            <div class="line-button">
              <a class="line-link" href="https://line.me/R/ti/p/%40652ivsas" target="_blank" rel="noopener noreferrer">
                LINEを追加して限定セッションを体験する</a>
            </div>
          </div>
        </div>

        <!-- 自己紹介 -->
        <div class="profile" id="menu-profile">
          <h2 class="profile-title">
            <span class="un-d">自己紹介</span>
          </h2>
          <div class="profile-content flex-rc">
            <img class="profile-image" src="images/profile-min.jpg" alt="プロフィール写真の表示に失敗しました">
            <div class="profile-text po-re">
              <p class="profile-text-size"><span class="bold">
                  コーチ / コーチングトレーナー<br>
                  たつろう</span>です<br>
                <br>
                <span class="bold">・好きなことやりたいことを見つけたい<br></span>
                <span class="bold">・ワクワクする人生にしたい！<br></span>
                <span class="bold">・とにかく自分らしく生きたい！<br></span>
                <br>
                というあなたを応援したい！！<br>
                <br>
                ★新卒一年目で大手ゼネコンから転職する時も<br>
                ★コーチとして活動する時も<br>
                ★自分ビジネスで起業する時も<br>
                <br>
                3つの人生の大きな分岐点もコーチングと共に乗り越えてきた
                僕だからこそあなたにコーチングを届けたい！！<br>
                自分の人生に希望を捨てていませんか？<br>
                まだまだ、コーチングであなたは変われますよ！<br>
                今のあなたが変われば、あなたの未来が変わります！<br>
                コーチングセッションで劇的に人生が変わる人多数！！<br>
              </p>
              <br>
              <a href="https://note.com/rorrou/n/n41cf4aea0b8c" class="bold">【コーチングへの想いを綴ったnoteへ飛ぶ】</a>
              <div class="back-box"></div>
            </div>
          </div>
          <div class="sns" id="menu-sns">
            <a href="https://www.facebook.com/soccer.cr.love/" target="_blank" rel="noopener noreferrer">
              <i class="sns-icon fab fa-facebook-square fa-5x"></i>
            </a>
            <a href="https://twitter.com/tatsurolife" target="_blank" rel="noopener noreferrer">
              <i class="sns-icon fab fa-twitter fa-5x"></i>
            </a>
            <a href="https://www.instagram.com/tatsurocoach/" target="_blank" rel="noopener noreferrer">
              <i class="sns-icon fab fa-instagram fa-5x"></i>
            </a>
            <a href="https://www.youtube.com/channel/UCjyg8Wxid2ebvWEe8CPya1Q" target="_blank" rel="noopener noreferrer" class="youtube">
              <i class="sns-icon fab fa-youtube fa-5x"></i>
            </a>
          </div>
        </div>

        <!-- 体験者の声 -->
        <div class="experiencer" id="menu-experiencer">
          <h2 class="experiencer-title text-center">
            <span class="un-d">体験者の声</span>
          </h2>
          <div class="experiencer-contents flex-rc">
            <div class="experiencer-content po-re">
              <p class="experiencer-content-text">
                23歳 / 男性<br>
                <br>
                コーチングを受けたことで自分自身の心や言葉、行動に向き合えるようになりました。
                <br>そのことから自分も満たされ、成長を加速させることができました。<br>
                さらに、自分だけでなく他者との関係性も良くなったことを強く実感しました。
                コーチングがなければ今の自分はありません。<br>
                コーチングは僕にとって思考する上できっかけや気づきを与えてくれる存在です。<br>
                例えるなら、ソクラテスの問答書の様な印象です。
              </p>
              <div class="back-box"></div>
            </div>
            <div class="experiencer-content po-re">
              <p class="experiencer-content-text">
                24歳 / 男性<br>
                <br>
                一番の発見は論理的な思考が出来る自分を知れたことです。<br>
                何か上手くいかなかったときに「なぜ上手くいかなかったのか？」「どうしたら上手くいくのか？」と自問自答できる自分がいました。<br>
                上記のことからこれまでよりも時間を上手く使うことができるようになったり、簡潔に物事を伝えられる様になりました。<br>
                コーチングを受けると自分の見えていない部分が見えます。<br>
                「自分の可能性を活かし切れていないな」と感じるときにコーチングを受けると未来が変わりました。
              </p>
              <div class="back-box"></div>
            </div>
          </div>
        </div>

        <!-- もっと自分らしく生きたいあなたへ -->
        <div class="reason-wrapper" id="menu-reason">
          <div class="reason-inner">
            <h2 class="reason-title text-center">
              <span class="un-d">もっと自分らしく生きたい<br class="br-sp">あなたへ</span>
            </h2>
            <div class="po-re">
              <div class="cp_box">
                <input id="cp01" type="checkbox">
                <label for="cp01"></label>
                <div class="cp_container">
                  <p class="myself-text"><span class="bold">◆僕がコーチングをする理由は<br class="br-sp">「イキイキした世の中にするため」です。<br></span>
                    イキイキとはあなたが好きなことを見つけてそれに向かっていることです。人は好きなことややりたいことをしているときに一番輝きます。その好きなことややりたいことを見つける手段が「コーチング」です。コーチングでは、これまで以上にあなたがあなたと向き合うことになります。知らなかった自分と出会うこともあるでしょう。でも、それが本当のあなたなのです。私は本当のあなたを見つけて前に進むお手伝いをさせていただきます。一人では乗り越えられないことはたくさんあります。そのために「コーチ」がいるのです。
                    僕もコーチからコーチングを受けたことで自分らしく生きることができる様になりました。
                    コーチングに出会うまでは「このままでいいのかな？」「この仕事が本当にやりたいことかな？」のような漠然とした不安を抱えていました。たった60分のコーチングでその漠然とした不安はなくなり、それだけではく、自分が今後やりたいことを達成するための明確な希望を持つことができました。
                    そしてこれからは「このままでいいのかな？」「この仕事が本当にやりたいことかな？」のような漠然とした不安を抱えているあなたに「もっと自分らしく生きてもらうために」コーチングを届けます。
                    困ったときは自分ひとりで抱え込まずに誰かを頼ることで前に進むことができます。
                    頼ることは恥ずかしいことではありません、かっこいいことです。一緒にイキイキしたあなたを見つけましょう。
                  </p>
                  <div class="back-box"></div>
                </div>
              </div>
            </div>
          </div>
        </div>



        <!-- 自己開示 -->
        <div class="myself-wrapper">
          <div class="myself-inner">
            <h2 class="myself-title text-center">
              <span class="un-d">私もコーチングに<br class="br-sp">救われた人の一人です</span>
            </h2>
            <div class="myself-content po-re">
              <div class="cp_box">
                <input id="cp02" type="checkbox">
                <label for="cp02"></label>
                <div class="cp_container">
                  <p class="myself-text"><span class="bold">◆経歴<br></span>
                    1997年生まれ。名城大学建築学科卒業後、大手ゼネコンに施工管理として入社。<br>
                    自分のビジョンと会社でできることの相違を感じ、その違和感から11ヶ月で退社。その後、ビジョンが一致するITベンチャーに転職。8ヶ月プログラミングを教え、現場の最前線を経験。月間最高対応数などを記録し、現在はライフコーチとして学習・行動の管理を担う。「イキイキした世の中にしたい」「目の前の人を輝かせたい」という想いを胸に、転職と同時に兼業としてコーチ活動も本格化。コーチングセッション(1on1)に加え、コーチングトレーニング(コーチ育成)にも力を注ぐ。これまでに100以上の1on1セッション実施。コーチングトレーナーとして200回以上登壇し、平均満足度4.93を獲得。(5点満点中)。「コーチングを日本のインフラに」を実現するべく前に進み続けるコーチ。
                  </p>
                  <div class="back-box"></div>
                  <p class="myself-text"><span class="bold">◆自分を表すワード（人柄）<br></span>
                    習慣の鬼・早寝早起き・健康・自分軸・一貫性・イキイキ・天使
                  </p>
                  <div class="back-box"></div>
                  <p class="myself-text"><span class="bold">◆コーチングとの出会い<br></span>
                    コーチングとの出会いは忘れもしない2019年5月のAKIOBLOGさんのYouTubです。<br>
                    大学生のときに60人の古い友人やSNSで繋がったフリーランス、経営者の方々に夢や目標をひたすら聞くことをしていました。途中からわかったことが一つありました。みんな「夢や目標がない」ということです。せっかくお時間頂いているので、過去に夢中になったことや得意なことを深掘っていき、その人の夢や目標の発見に導いていくことをしていました。ときにはスタバで8時間話しっぱなしのこともありました。その時間が一瞬で過ぎ去ったことを今でも覚えています。そして、AKIOBLOGさんのYouTubeを見たときに「もしかして、あれ、コーチングだったのか？」が出会いです。（今思うとこの勘違いが僕の人生を大きく動かしました）
                  </p>
                  <div class="back-box"></div>
                  <p class="myself-text"><span class="bold">◆コーチになろうと決意した瞬間<br></span>
                    コーチングで目の前が開けて人生が変わるんだと実感したから。<br>
                    新卒で就職した会社で、自分のやりたいことができていないと感じた瞬間に「転職しよう」と決意しました。でもこの決意は確固たるものではなく「新卒で入った会社を一年以内で辞めて良いのかな？」「この先好きなことで生きていけるのかな？」など後ろめたさや不安で溢れていました。そんな状態だったからそこ、試しに受けてみたのが「コーチング」でした。コーチングセッションの一時間後にはこれまでの不安は消え去っていました。消え去ったどころか、転職先の会社から内定をもらっていました。もう一度言います。「内定をもらっていました」。これがコーチング（エフィカシー）の力です。具体的には、このときには第一希望の会社に行けることは既に決まっていて、そこの会社に入って何をしているか？何をしたいか？しか考えていませんでした。第一希望の会社から内定をもらえている自分を100％信じ切っていたのです。このときに「これがコーチングかぁ」と心の中で叫びました。そして僕と共鳴しだしました。ここで共鳴したことでより多くの人にコーチングを体験してもらいたいと心から感じるようになり「イキイキした世の中にする」というビジョンを掲げ毎日歩んでいます。
                  </p>
                </div>
              </div>
            </div>
            <!-- <div class="back-box"></div>  -->

          </div>
          <div class="line-button" id="menu-line">
            <a class="line-link" href="https://line.me/R/ti/p/%40652ivsas" target="_blank" rel="noopener noreferrer">
              LINEを追加して限定セッションを体験する</a>
          </div>

        </div>
    </main>
<%
=begin%>

    <footer class="footer text-center">
      <p>&copy;2020 Tatsurocoach</p>
    </footer>
<%
=end%>
  </div><!-- /.wrap -->
  <script src="https://unpkg.com/react@17/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js" crossorigin></script>
  <%
=begin%>
  <script src="./js/index.js"></script>
  <%
=end%>
</body>

</html>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <hr>

  <div class="content-wrapper">
    <div class="content-main margin-left">
      <div class="content-blogs">
        <% @blogs.sort.reverse.each do |blog| %>
          <div class="content-blog">
            <div class="blog-top-image">
              <%= link_to blog do %>
                <%= image_tag blog.avatar, class: 'image-size' %>
              <% end %>
            </div>
            <div class="blog-bottom">
              <div class="created-at">
                <i class="far fa-clock"></i>
                <%= blog.created_at.strftime('%Y-%m-%d') %>
              </div>
              <div class="blog-title">
                <%= blog.title %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="content-side">
      <div class="content-sidebar">
        <% if logged_in? %>
          <% if current_user.admin?%>
            <div class="new-post">
              <%= link_to '新規投稿', new_blog_path, class: 'btn btn-block btn-success btn-sm' %>
            </div>
          <% end %>
        <% end %>
        <div class="profile">
          <div class="profile-image">
            <%= image_tag "profile" %>
          </div>
          <div class="profile-text-blog">
            <h5>たつろう</h5>
          </div>
          <div class="profile-occupation">
            <p>コーチ / エンジニア</p>
          </div>
          <hr class="profile-hr">
          <div class="profile-content">
            <p>
              大学時代にFPに従事、その後大手建設ゼネコンを経てプログラミングとコーチングに出会う。現在は、プログラミングのメンター/ビジネスオーナーのコーチとして活動。<br>
              Udemyで多数教材を作成し来年春に向けて執筆中。<br>
              <br>
              「イキイキした世の中にする」ことをビジョンに掲げ、「目の前の人のキッカケ」になることに生きがいを感じる。<br>
              <br>
              "Nothing ventured, nothing gained"<br>
              "迷ったらやる"
            </p>
          </div>
        </div>
        <div class="tag-list">
          <% @tag_list.each do |list| %>
            <%= link_to list.tag_name, tag_blogs_path(tag_id: list.id) %>
            <%= "(#{list.blogs.count})" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/search.html.erb
<%= stylesheet_link_tag 'search', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <div class="content-wrapper">
    <div class="content-main">
      <div class="content-head">
        <div class="tag-name">
          <%= "#{@tag.tag_name}の投稿一覧" %>
        </div>
        <div class="tag-names">
          <% @tag_list.each do |list| %>
            <%= link_to list.tag_name, tag_blogs_path(tag_id: list.id) %>
            <%= "(#{@tag.blogs.count})" %>
          <% end %>
        </div>
      </div>
      <div class="content-blogs">
        <% @blogs.each do |blog| %>
          <div class="content-blog">
            <div class="blog-top-image">
              <% if blog.images[0] %>
                <%= link_to blog do %>
                  <%= image_tag blog.images[0].image_url.url, class: 'image-size' %>
                <% end %>
              <% end %>
            </div>
            <div class="blog-bottom">
              <div class="created-at">
                <i class="far fa-clock"></i>
                <%= blog.created_at.strftime('%Y-%m-%d') %>
              </div>
              <div class="blog-title">
                <%= blog.title %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<%= stylesheet_link_tag 'rich_text', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container">
  <div class="card my-5">
    <div class="card-image mt-3 text-center">
      <%= image_tag @blog.avatar %>
    </div>
    <div class="card-body">
      <div class="card-title">
        <h1>
          <%= @blog.title %>
        </h1>
        <div class="text-right">
          更新日<%= @blog.updated_at.strftime("%Y-%m-%d") %>
        </div>
      </div>
      <div class="card-text">
        <%= @blog.content %>
      </div>
      <div class="blog-tags">
        <%= "タグ：" %>
        <% @blog_tags.each do |tag| %>
          <%= link_to tag.tag_name, tag_blogs_path(tag_id: tag.id) %>
          <%= "(#{tag.blogs.count})" %>
        <% end %>
      </div>
    </div>
   </div>

  <% if logged_in? %>
    <% if current_user.admin?%>
      <%= link_to 'Edit', edit_blog_path(@blog) %> |
      <%= link_to 'Back', blogs_path %> |
      <%= link_to 'Destroy', @blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>

  <% if @blog.comments.present? %>
    <h3>コメント</h3>
    <% @blog.comments.each do |comment| %>
      <p>
        <%= comment.commenter %>: <%= comment %>
        <% unless guest_user%>
          <%= link_to '削除', [comment.blog, comment],
                    :confirm => 'よろしいですか？',
                    :method => :delete %>
        <% end %>
      </p>
    <% end %>
  <% end %>

  <% unless guest_user%>
    <h3>コメントを書く</h3>
    <%= form_for([@blog, @blog.comments.build]) do |f| %>
      <div class="field mb-2">
        <%= f.text_field :commenter, placeholder: 'お名前', class: 'form-control' %>
      </div>
      <div class="field mb-2">
        <%= f.text_area :body, placeholder: '本文を入力してください',class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit "投稿する", class: 'btn btn-block btn-success btn-sm' %>
      </div>
    <% end %>
  <% end %>
</div>